services:
    # Admin manager
    shuwee_admin.admin_manager:
        class: Wanjee\Shuwee\AdminBundle\Manager\AdminManager

    shuwee_admin.admin_abstract:
        class: Wanjee\Shuwee\AdminBundle\Admin\Admin
        calls:
            - [setDoctrine, ['@doctrine']]
        abstract: true

    # Routing
    shuwee_admin.admin_routing_helper:
        class: Wanjee\Shuwee\AdminBundle\Routing\Helper\AdminRoutingHelper
        arguments: ['@router']

    shuwee_admin.admin_routing_loader:
        class: Wanjee\Shuwee\AdminBundle\Routing\Loader\AdminLoader
        arguments: ['@shuwee_admin.admin_manager', '@shuwee_admin.admin_routing_helper']
        tags:
            - { name: routing.loader }

    # ParamConverter
    shuwee_admin.admin_param_converter:
        class: Wanjee\Shuwee\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: ['@shuwee_admin.admin_manager']
        tags:
            - { name: request.param_converter }

    # Twig
    shuwee_admin.admin_twig_extension:
        class: Wanjee\Shuwee\AdminBundle\Twig\AdminExtension
        arguments: ['@shuwee_admin.admin_manager', '@shuwee_admin.admin_routing_helper', '@security.authorization_checker', '@translator']
        public: false
        tags:
            - { name: twig.extension }

    shuwee_admin.datagrid_twig_extension:
        class: Wanjee\Shuwee\AdminBundle\Twig\DatagridExtension
        arguments: ['@translator', '@security.csrf.token_manager']
        public: false
        tags:
            - { name: twig.extension }

    # Datagrid
    shuwee_admin.datagrid:
            class: Wanjee\Shuwee\AdminBundle\Datagrid\Datagrid
            arguments: ['@knp_paginator', '@doctrine.orm.default_entity_manager', '@form.factory', '@security.authorization_checker']

    # Security
    shuwee_admin.security.user_manager:
        class: Wanjee\Shuwee\AdminBundle\Security\UserManager
        arguments: ['@security.encoder_factory', '@doctrine.orm.entity_manager']

    shuwee_admin.security.content_voter:
        class:      Wanjee\Shuwee\AdminBundle\Security\Voter\ContentVoter
        arguments: ['@shuwee_admin.admin_manager']
        public:     false
        tags:
           - { name: security.voter }

    # Form type extensions
    shuwee_admin.file_preview_type_extension:
        class: Wanjee\Shuwee\AdminBundle\Form\Extension\FilePreviewTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    shuwee_admin.help_extension:
        class: Wanjee\Shuwee\AdminBundle\Form\Extension\HelpExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    shuwee_admin.markdown_extension:
        class: Wanjee\Shuwee\AdminBundle\Form\Extension\MarkdownTextareaExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextareaType }

    shuwee_admin.group_extension:
        class: Wanjee\Shuwee\AdminBundle\Form\Extension\GroupExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    # Menu builder
    shuwee_admin.menu_builder:
        class: Wanjee\Shuwee\AdminBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]
        tags:
            - { name: knp_menu.menu_builder, method: sideMenu, alias: sideMenu }

    # Events listeners
    shuwee_admin.admin_configure_menu_listener:
        class: Wanjee\Shuwee\AdminBundle\EventListener\ConfigureMenuContentListener
        arguments: ['@shuwee_admin.admin_manager', '@shuwee_admin.admin_routing_helper', '@translator', '@security.authorization_checker']
        tags:
            - { name: kernel.event_listener, event: shuwee_admin.menu_configure, method: onMenuConfigure }
